In [2]:
import random
from tqdm.notebook import tqdm
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import copy
from torch_geometric.utils import degree
import torch
from torch import nn, optim, Tensor
from torch_sparse import SparseTensor, matmul

from torch_geometric.data import download_url, extract_zip
from torch_geometric.utils import structured_negative_sampling
from torch_geometric.nn.conv.gcn_conv import gcn_norm
from torch_geometric.typing import Adj
from torch_geometric.nn.conv import MessagePassing

from scipy import sparse

In [3]:
r_mat = np.array([[0, 0, 1, 1],
                  [1, 0, 1, 0],
                  [0, 1, 0, 0],])
print(r_mat)

[[0 0 1 1]
 [1 0 1 0]
 [0 1 0 0]]


In [4]:
r_mat_np_coo = sparse.coo_matrix(r_mat)
print(r_mat_np_coo)


  (0, 2)	1
  (0, 3)	1
  (1, 0)	1
  (1, 2)	1
  (2, 1)	1


In [5]:
r_mat_edge_index = [r_mat_np_coo.row, r_mat_np_coo.col]


print(r_mat_edge_index[0])
print(r_mat_edge_index[1])

[0 0 1 1 2]
[2 3 0 2 1]


In [6]:
r_mat_np_coo.todense()

matrix([[0, 0, 1, 1],
        [1, 0, 1, 0],
        [0, 1, 0, 0]])

# Doing using Pytorch

In [7]:
r_mat_edge_index = torch.LongTensor(np.array(r_mat_edge_index))

In [8]:
sparse_r_mat_edge_index = SparseTensor(row=r_mat_edge_index[0], col=r_mat_edge_index[1], sparse_sizes=(3, 4))
print(sparse_r_mat_edge_index)

SparseTensor(row=tensor([0, 0, 1, 1, 2]),
             col=tensor([2, 3, 0, 2, 1]),
             size=(3, 4), nnz=5, density=41.67%)


In [9]:
dense_r_mat_edge_index = sparse_r_mat_edge_index.to_dense()
print(dense_r_mat_edge_index)   

tensor([[0., 0., 1., 1.],
        [1., 0., 1., 0.],
        [0., 1., 0., 0.]])


In [2]:
# In Bipartiite Graphs, the adjacency matrix is a block matrix with the shape of (N, M), where N and M are the number of nodes in the two partitions.
# in order to convert interaction matrix of a bipartite graph to adjacency matrix, we need to convert the interaction matrix to a block matrix with the shape of (N+M, N+M)

#      ( 0    R )
#  A = ( R_T  0 )

def convert_r_mat_edge_index_to_adj_mat_edge_index(input_edge_index):
    R = torch.zeros((num_users, num_movies))
    
# convert sparse coo format to dense format to get R matrix
    for i in range(input_edge_index[0]):
        row_idx = input_edge_index[0][i]
        col_idx = input_edge_index[1][i]
        R[row_idx][col_idx] = 1


    R_transpose = torch.transpose(R, 0, 1)
    adj_mat = torch.zeros((num_users + num_movies, num_users + num_movies))
    adj_mat[:num_users, num_users:] = R.clone()
    adj_mat[num_users:, :num_users] = R_transpose.clone()
    adj_mat_coo = adj_mat.to_sparse_coo()
    adj_mat_coo = adj_mat_coo.indices()
    return adj_mat_coo

In [11]:
def convert_adj_mat_edge_index_to_r_mat_edge_index(input_edge_index: Tensor):
    A = torch.zeros((row_size+col_size, row_size+col_size))
    for i in range(input_edge_index[0]):
        row_idx = input_edge_index[0][i]
        col_idx = input_edge_index[1][i]
        A[row_idx][col_idx] = 1

    R = A[:row_size, row_size:]
    R_coo = torch.nonzero(R, as_tuple=False).T
    return R_coo

In [13]:
adj_mat_edge_index = convert_r_mat_edge_index_to_adj_mat_edge_index(r_mat_edge_index, 3, 4)
print(adj_mat_edge_index)

TypeError: only integer tensors of a single element can be converted to an index

In [ ]:
adj_mat = SparseTensor(row=adj_mat_edge_index[0], col=adj_mat_edge_index[1], sparse_sizes=(7, 7))

print(adj_mat.to_dense())

In [ ]:
convert_back_r_mat_edge_index = convert_adj_mat_edge_index_to_r_mat_edge_index(adj_mat_edge_index, 3, 4)

converted_back_to_r_mat = SparseTensor(row=convert_back_r_mat_edge_index[0], col=convert_back_r_mat_edge_index[1], sparse_sizes=(3, 4))

print(converted_back_to_r_mat.to_dense())